-- migration.sql
-- Migration Script to Migrate Canteen Management System from Firebase Firestore to Supabase PostgreSQL
-- Generated on 2026-06-30

-- Enable common extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Clean up existing tables in reverse order of dependencies (re-runnable script)
DROP TABLE IF EXISTS punch_events CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS pending_meal_requests CASCADE;
DROP TABLE IF EXISTS guest_coupon_requests CASCADE;
DROP TABLE IF EXISTS qr_cards CASCADE;
DROP TABLE IF EXISTS coupons CASCADE;
DROP TABLE IF EXISTS employees CASCADE;
DROP TABLE IF EXISTS contractors CASCADE;
DROP TABLE IF EXISTS menus CASCADE;

-- =========================================================================
-- 1. CONTRACTORS TABLE
-- =========================================================================
CREATE TABLE contractors (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    business_name TEXT NOT NULL UNIQUE,
    contractor_id TEXT NOT NULL UNIQUE, -- Login ID used in Angular auth
    password TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE contractors IS 'Stores contractor details including login credentials and business metadata';
COMMENT ON COLUMN contractors.id IS 'Primary key, supporting manual migration IDs and auto-increment';
COMMENT ON COLUMN contractors.business_name IS 'Unique business name, referenced by employees';
COMMENT ON COLUMN contractors.contractor_id IS 'Unique login ID used for authentication';

-- =========================================================================
-- 2. EMPLOYEES TABLE
-- =========================================================================
CREATE TABLE employees (
    id BIGINT PRIMARY KEY, -- Keep existing numerical IDs as BIGINT
    name TEXT NOT NULL,
    email TEXT,
    employee_id TEXT NOT NULL UNIQUE, -- Actual Employee badge ID (e.g. EMP001)
    password TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('admin', 'contractual employee', 'employee', 'canteen manager')),
    department TEXT,
    employee_category TEXT CHECK (employee_category IN ('Staff', 'Technician')),
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'deactivated')),
    contractor TEXT REFERENCES contractors(business_name) ON DELETE SET NULL, -- References business name
    permanent_qr_code TEXT UNIQUE,
    assigned_qr_card TEXT UNIQUE,
    last_redeemed_date TIMESTAMPTZ,
    last_morning_breakfast_date TIMESTAMPTZ,
    last_lunch_date TIMESTAMPTZ,
    last_evening_breakfast_date TIMESTAMPTZ,
    last_dinner_date TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE employees IS 'Stores company permanent and contractual employees';
COMMENT ON COLUMN employees.id IS 'Internal unique numeric ID (BIGINT) mapped from firestore';
COMMENT ON COLUMN employees.employee_id IS 'String badge ID, unique across the system';
COMMENT ON COLUMN employees.contractor IS 'References the parent business_name from contractors table';

-- =========================================================================
-- 3. COUPONS TABLE
-- =========================================================================
CREATE TABLE coupons (
    coupon_id TEXT PRIMARY KEY, -- Original text ID from Firestore
    employee_id BIGINT REFERENCES employees(id) ON DELETE CASCADE,
    contractor_id BIGINT REFERENCES contractors(id) ON DELETE CASCADE,
    date_issued TIMESTAMPTZ NOT NULL,
    status TEXT NOT NULL DEFAULT 'issued' CHECK (status IN ('issued', 'redeemed', 'expired')),
    redeem_date TIMESTAMPTZ,
    redemption_code TEXT NOT NULL UNIQUE,
    coupon_type TEXT NOT NULL CHECK (coupon_type IN ('Breakfast', 'Lunch/Dinner', 'Snacks', 'Beverage')),
    slot INTEGER,
    is_guest_coupon BOOLEAN NOT NULL DEFAULT FALSE,
    shared_by_employee_id BIGINT REFERENCES employees(id) ON DELETE SET NULL,
    guest_name TEXT,
    guest_company TEXT,
    batch_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE coupons IS 'Canteen food coupons issued to employees or contractors';
COMMENT ON COLUMN coupons.coupon_id IS 'Textual unique identifier from the firestore document key';
COMMENT ON COLUMN coupons.employee_id IS 'Associated employee ID (optional, for assigned coupons)';
COMMENT ON COLUMN coupons.contractor_id IS 'Associated contractor ID (optional, for contractor-pool coupons)';
COMMENT ON COLUMN coupons.redemption_code IS 'Secure unique random string used to validate/redeem coupons';

-- =========================================================================
-- 4. QR CARDS TABLE
-- =========================================================================
CREATE TABLE qr_cards (
    card_code TEXT PRIMARY KEY, -- Original qr card_code remains TEXT
    assigned BOOLEAN NOT NULL DEFAULT FALSE,
    employee_id BIGINT UNIQUE REFERENCES employees(id) ON DELETE SET NULL,
    employee_name TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE qr_cards IS 'Physical or static QR cards allocatable to employees';
COMMENT ON COLUMN qr_cards.card_code IS 'Primary key corresponding to code encoded in the physical QR';

-- =========================================================================
-- 5. GUEST COUPON REQUESTS TABLE
-- =========================================================================
CREATE TABLE guest_coupon_requests (
    id TEXT PRIMARY KEY, -- Textual unique ID
    employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    employee_name TEXT NOT NULL,
    guest_name TEXT NOT NULL,
    guest_company TEXT NOT NULL,
    coupon_type TEXT NOT NULL CHECK (coupon_type IN ('Breakfast', 'Lunch/Dinner', 'Snacks', 'Beverage')),
    status TEXT NOT NULL DEFAULT 'pending_employee' CHECK (status IN ('pending_employee', 'pending_admin', 'approved', 'rejected', 'redeemed')),
    request_date TIMESTAMPTZ NOT NULL,
    decision_date TIMESTAMPTZ,
    admin_id BIGINT REFERENCES employees(id) ON DELETE SET NULL,
    rejection_reason TEXT,
    generated_coupon_id TEXT REFERENCES coupons(coupon_id) ON DELETE SET NULL,
    requested_by TEXT CHECK (requested_by IN ('employee', 'canteen_manager')),
    employee_decision_date TIMESTAMPTZ,
    employee_approved_by BIGINT REFERENCES employees(id) ON DELETE SET NULL,
    employee_rejected_reason TEXT,
    served_date TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE guest_coupon_requests IS 'Log of guest coupon generation approvals, supporting double-tier confirmation';

-- =========================================================================
-- 6. PENDING MEAL REQUESTS TABLE
-- =========================================================================
CREATE TABLE pending_meal_requests (
    id TEXT PRIMARY KEY, -- Textual unique ID mapping from requestId
    employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    employee_name TEXT NOT NULL,
    meal_type TEXT NOT NULL CHECK (meal_type IN ('morning', 'lunch', 'evening', 'dinner')),
    meal_date TIMESTAMPTZ NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('pending', 'completed')),
    is_coupon_adjusted BOOLEAN NOT NULL DEFAULT FALSE,
    adjusted_coupon_id TEXT REFERENCES coupons(coupon_id) ON DELETE SET NULL,
    adjustment_date TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE pending_meal_requests IS 'Meal requests awaiting reconciliation or automatic billing';

-- =========================================================================
-- 7. MENUS TABLE
-- =========================================================================
CREATE TABLE menus (
    id TEXT PRIMARY KEY, -- YYYY-MM-DD format as document key
    date TIMESTAMPTZ NOT NULL,
    breakfast_menu TEXT NOT NULL,
    lunch_dinner_menu TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE menus IS 'Stores daily cafeteria menu rosters';

-- =========================================================================
-- 8. NOTIFICATIONS TABLE
-- =========================================================================
CREATE TABLE notifications (
    id TEXT PRIMARY KEY, -- original textual ID
    employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    message TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('new_coupon', 'system', 'guest_pass_request')),
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL,
    related_request_id TEXT REFERENCES guest_coupon_requests(id) ON DELETE SET NULL,
    requester_employee_id BIGINT REFERENCES employees(id) ON DELETE SET NULL,
    related_coupon_id TEXT REFERENCES coupons(coupon_id) ON DELETE SET NULL
);

COMMENT ON TABLE notifications IS 'Push/In-app alerts and notifications generated for users';

-- =========================================================================
-- 9. PUNCH EVENTS TABLE
-- =========================================================================
CREATE TABLE punch_events (
    id TEXT PRIMARY KEY, -- original unique ID
    employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    result_type TEXT NOT NULL CHECK (result_type IN ('redeemed', 'already_redeemed', 'not_available', 'error')),
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

COMMENT ON TABLE punch_events IS 'Audit logs recording real-time scan occurrences from physical punch terminals';

-- =========================================================================
-- INDEXES FOR HIGH-PERFORMANCE QUERIES
-- =========================================================================

-- Employees lookup & filters
CREATE INDEX idx_employees_role ON employees(role);
CREATE INDEX idx_employees_status ON employees(status);
CREATE INDEX idx_employees_contractor ON employees(contractor);

-- Coupons queries (e.g. finding active, checking batch, checking code)
CREATE INDEX idx_coupons_employee_id ON coupons(employee_id);
CREATE INDEX idx_coupons_contractor_id ON coupons(contractor_id);
CREATE INDEX idx_coupons_coupon_type ON coupons(coupon_type);
CREATE INDEX idx_coupons_status ON coupons(status);
CREATE INDEX idx_coupons_batch_id ON coupons(batch_id);

-- Qr Cards reference
CREATE INDEX idx_qr_cards_employee_id ON qr_cards(employee_id);

-- Guest pass approvals & status checking
CREATE INDEX idx_guest_coupon_requests_employee_id ON guest_coupon_requests(employee_id);
CREATE INDEX idx_guest_coupon_requests_status ON guest_coupon_requests(status);
CREATE INDEX idx_guest_coupon_requests_request_date ON guest_coupon_requests(request_date);

-- Pending meal allocations
CREATE INDEX idx_pending_meal_requests_employee_id ON pending_meal_requests(employee_id);
CREATE INDEX idx_pending_meal_requests_meal_date ON pending_meal_requests(meal_date);
CREATE INDEX idx_pending_meal_requests_status ON pending_meal_requests(status);

-- Menus index
CREATE INDEX idx_menus_date ON menus(date);

-- Notifications delivery
CREATE INDEX idx_notifications_employee_id ON notifications(employee_id);
CREATE INDEX idx_notifications_is_read ON notifications(is_read);
CREATE INDEX idx_notifications_created_at ON notifications(created_at);

-- Punch events log
CREATE INDEX idx_punch_events_employee_id ON punch_events(employee_id);
CREATE INDEX idx_punch_events_created_at ON punch_events(created_at);
