-- migration.sql
-- Migration Script to Migrate Canteen Management System from Firebase Firestore to Supabase PostgreSQL
-- Generated on 2026-06-30

-- Enable common extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Clean up existing tables in reverse order of dependencies (re-runnable script)
DROP TABLE IF EXISTS punch_events CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS pending_meal_requests CASCADE;
DROP TABLE IF EXISTS guest_coupon_requests CASCADE;
DROP TABLE IF EXISTS qr_cards CASCADE;
DROP TABLE IF EXISTS coupons CASCADE;
DROP TABLE IF EXISTS employees CASCADE;
DROP TABLE IF EXISTS contractors CASCADE;
DROP TABLE IF EXISTS menus CASCADE;

-- =========================================================================
-- 1. CONTRACTORS TABLE
-- =========================================================================
CREATE TABLE contractors (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    business_name TEXT NOT NULL UNIQUE,
    contractor_id TEXT NOT NULL UNIQUE, -- Login ID used in Angular auth
    password TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE contractors IS 'Stores contractor details including login credentials and business metadata';
COMMENT ON COLUMN contractors.id IS 'Primary key, supporting manual migration IDs and auto-increment';
COMMENT ON COLUMN contractors.business_name IS 'Unique business name, referenced by employees';
COMMENT ON COLUMN contractors.contractor_id IS 'Unique login ID used for authentication';

-- =========================================================================
-- 2. EMPLOYEES TABLE
-- =========================================================================
CREATE TABLE employees (
    id BIGINT PRIMARY KEY, -- Keep existing numerical IDs as BIGINT
    name TEXT NOT NULL,
    email TEXT,
    employee_id TEXT NOT NULL UNIQUE, -- Actual Employee badge ID (e.g. EMP001)
    password TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('admin', 'contractual employee', 'employee', 'canteen manager')),
    department TEXT,
    employee_category TEXT CHECK (employee_category IN ('Staff', 'Technician')),
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'deactivated')),
    contractor TEXT REFERENCES contractors(business_name) ON DELETE SET NULL, -- References business name
    permanent_qr_code TEXT UNIQUE,
    assigned_qr_card TEXT UNIQUE,
    last_redeemed_date TIMESTAMPTZ,
    last_morning_breakfast_date TIMESTAMPTZ,
    last_lunch_date TIMESTAMPTZ,
    last_evening_breakfast_date TIMESTAMPTZ,
    last_dinner_date TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE employees IS 'Stores company permanent and contractual employees';
COMMENT ON COLUMN employees.id IS 'Internal unique numeric ID (BIGINT) mapped from firestore';
COMMENT ON COLUMN employees.employee_id IS 'String badge ID, unique across the system';
COMMENT ON COLUMN employees.contractor IS 'References the parent business_name from contractors table';

-- =========================================================================
-- 3. COUPONS TABLE
-- =========================================================================
CREATE TABLE coupons (
    coupon_id TEXT PRIMARY KEY, -- Original text ID from Firestore
    employee_id BIGINT REFERENCES employees(id) ON DELETE CASCADE,
    contractor_id BIGINT REFERENCES contractors(id) ON DELETE CASCADE,
    date_issued TIMESTAMPTZ NOT NULL,
    status TEXT NOT NULL DEFAULT 'issued' CHECK (status IN ('issued', 'redeemed', 'expired')),
    redeem_date TIMESTAMPTZ,
    redemption_code TEXT NOT NULL UNIQUE,
    coupon_type TEXT NOT NULL CHECK (coupon_type IN ('Breakfast', 'Lunch/Dinner', 'Snacks', 'Beverage')),
    slot INTEGER,
    is_guest_coupon BOOLEAN NOT NULL DEFAULT FALSE,
    shared_by_employee_id BIGINT REFERENCES employees(id) ON DELETE SET NULL,
    guest_name TEXT,
    guest_company TEXT,
    batch_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE coupons IS 'Canteen food coupons issued to employees or contractors';
COMMENT ON COLUMN coupons.coupon_id IS 'Textual unique identifier from the firestore document key';
COMMENT ON COLUMN coupons.employee_id IS 'Associated employee ID (optional, for assigned coupons)';
COMMENT ON COLUMN coupons.contractor_id IS 'Associated contractor ID (optional, for contractor-pool coupons)';
COMMENT ON COLUMN coupons.redemption_code IS 'Secure unique random string used to validate/redeem coupons';

-- =========================================================================
-- 4. QR CARDS TABLE
-- =========================================================================
CREATE TABLE qr_cards (
    card_code TEXT PRIMARY KEY, -- Original qr card_code remains TEXT
    assigned BOOLEAN NOT NULL DEFAULT FALSE,
    employee_id BIGINT UNIQUE REFERENCES employees(id) ON DELETE SET NULL,
    employee_name TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE qr_cards IS 'Physical or static QR cards allocatable to employees';
COMMENT ON COLUMN qr_cards.card_code IS 'Primary key corresponding to code encoded in the physical QR';

-- =========================================================================
-- 5. GUEST COUPON REQUESTS TABLE
-- =========================================================================
CREATE TABLE guest_coupon_requests (
    id TEXT PRIMARY KEY, -- Textual unique ID
    employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    employee_name TEXT NOT NULL,
    guest_name TEXT NOT NULL,
    guest_company TEXT NOT NULL,
    coupon_type TEXT NOT NULL CHECK (coupon_type IN ('Breakfast', 'Lunch/Dinner', 'Snacks', 'Beverage')),
    status TEXT NOT NULL DEFAULT 'pending_employee' CHECK (status IN ('pending_employee', 'pending_admin', 'approved', 'rejected', 'redeemed')),
    request_date TIMESTAMPTZ NOT NULL,
    decision_date TIMESTAMPTZ,
    admin_id BIGINT REFERENCES employees(id) ON DELETE SET NULL,
    rejection_reason TEXT,
    generated_coupon_id TEXT REFERENCES coupons(coupon_id) ON DELETE SET NULL,
    requested_by TEXT CHECK (requested_by IN ('employee', 'canteen_manager')),
    employee_decision_date TIMESTAMPTZ,
    employee_approved_by BIGINT REFERENCES employees(id) ON DELETE SET NULL,
    employee_rejected_reason TEXT,
    served_date TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE guest_coupon_requests IS 'Log of guest coupon generation approvals, supporting double-tier confirmation';

-- =========================================================================
-- 6. PENDING MEAL REQUESTS TABLE
-- =========================================================================
CREATE TABLE pending_meal_requests (
    id TEXT PRIMARY KEY, -- Textual unique ID mapping from requestId
    employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    employee_name TEXT NOT NULL,
    meal_type TEXT NOT NULL CHECK (meal_type IN ('morning', 'lunch', 'evening', 'dinner')),
    meal_date TIMESTAMPTZ NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('pending', 'completed')),
    is_coupon_adjusted BOOLEAN NOT NULL DEFAULT FALSE,
    adjusted_coupon_id TEXT REFERENCES coupons(coupon_id) ON DELETE SET NULL,
    adjustment_date TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE pending_meal_requests IS 'Meal requests awaiting reconciliation or automatic billing';

-- =========================================================================
-- 7. MENUS TABLE
-- =========================================================================
CREATE TABLE menus (
    id TEXT PRIMARY KEY, -- YYYY-MM-DD format as document key
    date TIMESTAMPTZ NOT NULL,
    breakfast_menu TEXT NOT NULL,
    lunch_dinner_menu TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE menus IS 'Stores daily cafeteria menu rosters';

-- =========================================================================
-- 8. NOTIFICATIONS TABLE
-- =========================================================================
CREATE TABLE notifications (
    id TEXT PRIMARY KEY, -- original textual ID
    employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    message TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('new_coupon', 'system', 'guest_pass_request')),
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL,
    related_request_id TEXT REFERENCES guest_coupon_requests(id) ON DELETE SET NULL,
    requester_employee_id BIGINT REFERENCES employees(id) ON DELETE SET NULL,
    related_coupon_id TEXT REFERENCES coupons(coupon_id) ON DELETE SET NULL
);

COMMENT ON TABLE notifications IS 'Push/In-app alerts and notifications generated for users';

-- =========================================================================
-- 9. PUNCH EVENTS TABLE
-- =========================================================================
CREATE TABLE punch_events (
    id TEXT PRIMARY KEY, -- original unique ID
    employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    result_type TEXT NOT NULL CHECK (result_type IN ('redeemed', 'already_redeemed', 'not_available', 'error')),
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

COMMENT ON TABLE punch_events IS 'Audit logs recording real-time scan occurrences from physical punch terminals';

-- =========================================================================
-- INDEXES FOR HIGH-PERFORMANCE QUERIES
-- =========================================================================

-- Employees lookup & filters
CREATE INDEX idx_employees_role ON employees(role);
CREATE INDEX idx_employees_status ON employees(status);
CREATE INDEX idx_employees_contractor ON employees(contractor);

-- Coupons queries (e.g. finding active, checking batch, checking code)
CREATE INDEX idx_coupons_employee_id ON coupons(employee_id);
CREATE INDEX idx_coupons_contractor_id ON coupons(contractor_id);
CREATE INDEX idx_coupons_coupon_type ON coupons(coupon_type);
CREATE INDEX idx_coupons_status ON coupons(status);
CREATE INDEX idx_coupons_batch_id ON coupons(batch_id);

-- Qr Cards reference
CREATE INDEX idx_qr_cards_employee_id ON qr_cards(employee_id);

-- Guest pass approvals & status checking
CREATE INDEX idx_guest_coupon_requests_employee_id ON guest_coupon_requests(employee_id);
CREATE INDEX idx_guest_coupon_requests_status ON guest_coupon_requests(status);
CREATE INDEX idx_guest_coupon_requests_request_date ON guest_coupon_requests(request_date);

-- Pending meal allocations
CREATE INDEX idx_pending_meal_requests_employee_id ON pending_meal_requests(employee_id);
CREATE INDEX idx_pending_meal_requests_meal_date ON pending_meal_requests(meal_date);
CREATE INDEX idx_pending_meal_requests_status ON pending_meal_requests(status);

-- Menus index
CREATE INDEX idx_menus_date ON menus(date);

-- Notifications delivery
CREATE INDEX idx_notifications_employee_id ON notifications(employee_id);
CREATE INDEX idx_notifications_is_read ON notifications(is_read);
CREATE INDEX idx_notifications_created_at ON notifications(created_at);

-- Punch events log
CREATE INDEX idx_punch_events_employee_id ON punch_events(employee_id);
CREATE INDEX idx_punch_events_created_at ON punch_events(created_at);

-- =========================================================================
-- 10. ATOMIC COUPON REDEMPTION WITH ROW LOCKING
-- =========================================================================

CREATE OR REPLACE FUNCTION redeem_coupon_atomic(
    p_coupon_id TEXT,
    p_employee_id BIGINT,
    p_meal_type TEXT, -- 'morning', 'lunch', 'evening', 'dinner', or NULL
    p_punch_event_id TEXT,
    p_notif_id TEXT,
    p_success_message TEXT
) RETURNS JSONB AS $$
DECLARE
    v_coupon_status TEXT;
    v_coupon_type TEXT;
    v_employee_status TEXT;
    v_last_morning_date DATE;
    v_last_lunch_date DATE;
    v_last_evening_date DATE;
    v_last_dinner_date DATE;
    v_today DATE := (NOW() AT TIME ZONE 'Asia/Kolkata')::DATE;
    v_now TIMESTAMPTZ := NOW();
BEGIN
    -- 1. Acquire row lock on the coupon and retrieve its current status
    SELECT status, coupon_type INTO v_coupon_status, v_coupon_type
    FROM coupons
    WHERE coupon_id = p_coupon_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RETURN jsonb_build_object('success', false, 'message', 'Coupon not found');
    END IF;

    IF v_coupon_status = 'redeemed' THEN
        RETURN jsonb_build_object('success', false, 'message', 'Already Redeemed');
    END IF;

    IF v_coupon_status = 'expired' THEN
        RETURN jsonb_build_object('success', false, 'message', 'This coupon is expired');
    END IF;

    -- 2. Retrieve and lock the employee row (if employee_id is specified)
    IF p_employee_id IS NOT NULL AND p_employee_id > 0 THEN
        SELECT status, 
               (last_morning_breakfast_date AT TIME ZONE 'Asia/Kolkata')::DATE, 
               (last_lunch_date AT TIME ZONE 'Asia/Kolkata')::DATE, 
               (last_evening_breakfast_date AT TIME ZONE 'Asia/Kolkata')::DATE, 
               (last_dinner_date AT TIME ZONE 'Asia/Kolkata')::DATE
        INTO v_employee_status, 
             v_last_morning_date, 
             v_last_lunch_date, 
             v_last_evening_date, 
             v_last_dinner_date
        FROM employees
        WHERE id = p_employee_id
        FOR UPDATE;

        IF NOT FOUND THEN
            RETURN jsonb_build_object('success', false, 'message', 'Employee not found');
        END IF;

        IF v_employee_status = 'deactivated' THEN
            RETURN jsonb_build_object('success', false, 'message', 'Employee account is deactivated');
        END IF;

        -- 3. Check for double-redemption of same meal type today
        IF p_meal_type IS NOT NULL THEN
            IF p_meal_type = 'morning' AND v_last_morning_date = v_today THEN
                RETURN jsonb_build_object('success', false, 'message', 'Already Redeemed');
            ELSIF p_meal_type = 'lunch' AND v_last_lunch_date = v_today THEN
                RETURN jsonb_build_object('success', false, 'message', 'Already Redeemed');
            ELSIF p_meal_type = 'evening' AND v_last_evening_date = v_today THEN
                RETURN jsonb_build_object('success', false, 'message', 'Already Redeemed');
            ELSIF p_meal_type = 'dinner' AND v_last_dinner_date = v_today THEN
                RETURN jsonb_build_object('success', false, 'message', 'Already Redeemed');
            END IF;
        END IF;

        -- 4. Update Employee fields: last_redeemed_date and the meal-specific column
        UPDATE employees
        SET last_redeemed_date = v_now,
            last_morning_breakfast_date = CASE WHEN p_meal_type = 'morning' THEN v_now ELSE last_morning_breakfast_date END,
            last_lunch_date = CASE WHEN p_meal_type = 'lunch' THEN v_now ELSE last_lunch_date END,
            last_evening_breakfast_date = CASE WHEN p_meal_type = 'evening' THEN v_now ELSE last_evening_breakfast_date END,
            last_dinner_date = CASE WHEN p_meal_type = 'dinner' THEN v_now ELSE last_dinner_date END
        WHERE id = p_employee_id;
    END IF;

    -- 5. Update Coupon Status to redeemed
    UPDATE coupons
    SET status = 'redeemed',
        redeem_date = v_now
    WHERE coupon_id = p_coupon_id;

    -- 6. Insert Audit Punch Event
    IF p_punch_event_id IS NOT NULL THEN
        INSERT INTO punch_events (id, employee_id, result_type, message, created_at)
        VALUES (p_punch_event_id, COALESCE(p_employee_id, 0), 'redeemed', p_success_message, v_now);
    END IF;

    -- 7. Insert Notification
    IF p_notif_id IS NOT NULL AND p_employee_id IS NOT NULL AND p_employee_id > 0 THEN
        INSERT INTO notifications (id, employee_id, message, type, is_read, created_at, related_coupon_id)
        VALUES (p_notif_id, p_employee_id, p_success_message, 'system', FALSE, v_now, p_coupon_id);
    END IF;

    -- 8. Update guest_coupon_requests if applicable
    UPDATE guest_coupon_requests
    SET status = 'redeemed',
        served_date = v_now
    WHERE generated_coupon_id = p_coupon_id;

    RETURN jsonb_build_object(
        'success', true, 
        'message', p_success_message,
        'redeem_date', v_now::TEXT
    );
END;
$$ LANGUAGE plpgsql
SET timezone = 'Asia/Kolkata';
